In [ ]:
# Factcheck

In [1]:
import glob
import pandas as pd

objects_df = pd.read_hdf('/home/richard/Git/bbk-mqaf/data/latest/factcheck.h5')

In [2]:
objects_df

,[systemNumber,completeness:TOTAL,existence:systemNumber,existence:productionDates,existence:materials,cardinality:systemNumber,cardinality:productionDates,cardinality:materials,materials:entityabsence:productionDates:factCheck,ruleCatalog:score]
0,O1243715,1.0,1,1,1,1,1,2,1.0,0
1,O1243718,1.0,1,1,1,1,1,4,1.0,0
2,O1243716,1.0,1,1,1,1,1,4,1.0,0
3,O1243711,1.0,1,1,1,1,1,2,1.0,0
4,O1243714,1.0,1,1,1,1,1,3,1.0,0
...,...,...,...,...,...,...,...,...,...,...
8759,O191369,1.0,1,1,1,1,1,1,1.0,0
8760,O191368,1.0,1,1,1,1,1,1,1.0,0
8761,O191367,1.0,1,1,1,1,1,1,1.0,0
8762,O191366,1.0,1,1,1,1,1,1,1.0,0
8763,O191365,1.0,1,1,1,1,1,1,1.0,0

In [6]:
# Remove objects with positive score

falseobjects_df = objects_df[objects_df[" ruleCatalog:score]"] < 0]

In [10]:
falseobjects_df['[systemNumber']

4927     O697362
7306    O1314742
1416    O1035294
7171    O1248745
5166     O138803
7667     O320618
2366     O372219
4768     O106721
4770     O106719
4777     O106711
8534     O142454
3256    O1413507
9269      O10416
8050      O76632
Name: [systemNumber, dtype: object