# Factcheck (Techniques)

This compares the object's production dates with the object' techniques, and identifies any cases where a technique is stated that did not exist at the time of the object's known production. This could indicate:
  * A typo in dates
  * A production date range given that could be more tightly specified (e.g. if a technique was only available from a certain date, this sets the earliest bound of the date range, rather than a century or decade range being used)

In [1]:
import glob
import pandas as pd

objects_df = pd.read_hdf('/home/richard/Git/bbk-mqaf/data/latest/factcheck-techniques.h5')

In [2]:
# Remove objects with positive score

falseobjects_df = objects_df[objects_df[" ruleCatalog:score]"] < 0]

In [4]:
print(f"Total Objects {len(objects_df)} of which {len(falseobjects_df)} contain possible dating or material errors")

Total Objects 1238433 of which 855) contain possible dating or material errors

In [8]:
falseobjects_df.sample(20)

,[systemNumber,completeness:TOTAL,existence:systemNumber,existence:productionDates,existence:techniques,cardinality:systemNumber,cardinality:productionDates,cardinality:techniques,techniques:entityabsence:productionDates:factCheck,ruleCatalog:score]
1344,O1277537,1.0,1,1,1,1,1,2,-1.0,-1
617,O638762,1.0,1,1,1,1,1,2,-1.0,-1
3641,O1140665,1.0,1,1,1,1,1,2,-1.0,-1
6009,O1403545,1.0,1,1,1,1,1,2,-1.0,-1
104,O121767,1.0,1,1,1,1,1,2,-1.0,-1
3510,O702133,1.0,1,1,1,1,1,4,-1.0,-1
2439,O1279968,1.0,1,1,1,1,1,2,-1.0,-1
2162,O1329730,1.0,1,1,1,1,1,2,-1.0,-1
8476,O1398859,1.0,1,1,1,1,1,2,-1.0,-1
7739,O1397256,1.0,1,1,1,1,1,2,-1.0,-1
4016,O752409,1.0,1,1,1,1,1,1,-1.0,-1
7792,O1397004,1.0,1,1,1,1,1,2,-1.0,-1
621,O638758,1.0,1,1,1,1,1,2,-1.0,-1
1692,O1277150,1.0,1,1,1,1,1,2,-1.0,-1
2998,O702145,1.0,1,1,1,1,1,4,-1.0,-1
627,O638752,1.0,1,1,1,1,1,2,-1.0,-1
8596,O1397785,1.0,1,1,1,1,1,2,-1.0,-1
2553,O1279846,1.0,1,1,1,1,1,2,-1.0,-1
8342,O1397153,1.0,1,1,1,1,1,2,-1.0,-1
5238,O1141451,1.0,1,1,1,1,1,2,-1.0,-1